version: "3.8"

services:
  localstack:
    container_name: "localstack"
#    image: localstack/localstack-pro:2.3.2
    image: localstack/localstack-pro:latest
    networks:
      - devnet
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
#      - "53:53"                # DNS config (only required for Pro)
#      - "53:53/udp"            # DNS config (only required for Pro)
      - "443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-west-2
      - LOCALSTACK_HOSTNAME=${LOCALSTACK_HOSTNAME}
      - LAMBDA_DOCKER_NETWORK=devnet
      - HOSTNAME_EXTERNAL=host.docker.internal
      - LAMBDA_EXECUTOR=docker-reuse
      - REQUIRE_PRO=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./ls_volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  devnet:
    name: devnet
    driver: bridge
    ipam:
      config:
        - subnet: "169.254.170.0/24"
          gateway: 169.254.170.1
